[package]
name = "reactive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-fn-stream = "0.2.0"
futures = "0.3.28"
tokio = "1.29.1"
